apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-pod
spec:
  selector:
    matchLabels:
      run: couchdb-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: couchdb-pod
    spec:
      containers:
      - name: couchdb
        image: couchdb
        env:
        - name: COUCHDB_USER
          value: msrcosmos
        - name: COUCHDB_PASSWORD
          value: msrcosmos
        ports:
        - containerPort: 5984
